### ISSUE TITLE
Add usage instructions to the README. 

### ISSUE THREAD

**Issue by LinuxIsCool** [CommonsBuild/tec-hatch#45]
I cloned, ran `yarn install` then `yarn start`. I get the following: 

![image](https://user-images.githubusercontent.com/31582215/110741682-eee0b900-81e9-11eb-8e75-70020034012a.png)

**Comment by PJColombo** [comment]
Hey @LinuxIsCool,  this PR includes a `README.md` update with a `Usage` section.
