### ISSUE TITLE
Nobody be buyin' nothin in these parts

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/tec-hatch#6]
<img width="212" alt="Screen Shot 2020-12-23 at 4 37 45 PM" src="https://user-images.githubusercontent.com/14945613/103038757-8af60f00-456f-11eb-9fc7-f77553bf03b1.png">

Please change to "Mint TESTTEC" in all places

**Comment by fioreb** [comment]
I make the changes to the Hatch designs in the Figma file.
